version: '3.8'
services:
  nginx:
    build: ./nginx/
    ports:
      - '8080:80'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - 'article-api-nginx'
      - 'comment-api-nginx'
