version: '3.8'
services:
  router:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - 'article-api-nginx'
      - 'comment-api-nginx'
